version: '3.8'

services:
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    env_file:
      - ./services/user-service/.env
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - postgres
    networks:
      - app-network

  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
    env_file:
      - ./services/product-service/.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres_1
      - user-service
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USER}
    ports:
      - "5433:5433"
    volumes:
      - postgres_data_user:/var/lib/postgresql/data
    networks:
      - app-network
  

  postgres_1:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_PRODUCT}
    ports:
      - "5434:5434"
    volumes:
      - postgres_data_product:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data_user:
  postgres_data_product:

